[자동차 경주 게임] 노력 미션 제출합니다.
REVENGE-WOOTECO/java-racingcar-precourse pull request #2
Opened 2021-12-04 09:26 UTC by yuminhwan

이번 미션을 하며 코드 리뷰의 힘을 알게 된 것 같습니다!  감사드립니다!! 
이번에는 테스트코드를 작성해보았는데 아직 한참 멀은 것 같습니다. 😂
다시 한번 따끔한 충고 부탁드립니다!!

## 질문
- 객체의 불변성을 위해서 `this.cars = new ArrayList<>(cars);`와 같은 방식말고 정적 메소드 팩토리를 사용하였습니다.  단순히 `List` 를 `ArrayList`로 주입? 하기 싫어서 정적 메소드 팩토리를 사용했는 데 옳바른 방식 일까요? 
- 테스트만을 위한 메소드를 만들어도 될까요? `Cars`에 있는 `List<Car> cars`의 사이즈를 테스트하기 위해 `size()`라는 메소드를 만들고 테스트 후 지우는 방식으로 했는 데 매우 비효율적인 방식인 것 같습니다.

2021-12-05 08:49 UTC, lns13301 requested changes
반갑습니다. 노력님! 💪
이번 미션을 함께할 우아한테크코스 3기 와일더입니다. 🃏 

기능 구현도 잘해주셨고, 테스트 코드, 클래스 분리, 새로운 시도, 클린 코드 등 다양한 시도를 하신 흔적이 보였어요! 💯 
미션도 빠르게 구현해주신걸보니 Java 프로그래밍에 익숙하신 것 같아요! 👍

질문하신 내용, 수정해야할 부분, 고민하고 생각해볼 부분으로 나누어서 피드백을 드렸어요. 동일한 내용에 대한 피드백(매직넘버, 주석제거 등)은 한번만 남겨두었으니 참고하셔서 전체적으로 고민해보시면 좋겠어요. 😁

간혹 설명이 길어지다보면 이해가 잘안되게 피드백을 남겼을 수 있으니 확인해보시고 이해가 안되면 코멘트 달아주세요.😊 추가적으로 궁금한 질문도 코멘트 남겨주시면 확인하고 답변 달아드리겠습니다.

수정하고 리뷰 재요청해 주세요. 😀

2021-12-05 08:49 UTC, lns13301 commented on docs/README.md
> +## 🔥 구현할 기능 목록
기능 구현 정리 👍

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +    private static final String ERROR_WHITE_SPACE_NAME = "[ERROR] 공백인 이름은 입력할 수 없습니다. 다시 입력해주세요.";
노력님은 어떤 기준으로 매직넘버를 상수로 관리하시나요? 🤔 

저는 상수로 관리하는 상황은 이럴 때 사용한다고 생각해요.

1. 중복 사용
2. 의미를 파악할 수 없을 경우

이런 메시지의 경우 중복 사용되고 있지않고, 의미를 파악할 수 있는 문장이라 상수로 관리하지 않아도 된다고 생각해요.
흘러가듯 코드를 읽고 있다가 `ERROR_WHITE_SPACE_NAME` 이 어떤 메시지의 형태인지 상수를 체크해야하는 번거로움이 생길 수 있어서 이런 경우에 저는 상수를 사용하지 않아요. 이 부분은 <b>개인마다 생각이 다른 부분</b>이라 노력님의 생각이 궁금하네요.

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +        if (name.length() > 5) {
입력 길이 검증 👍 
저는 길이제한인 '5' 의 경우에 의미를 파악하기 힘들다고 생각하여 상수로 관리해야 한다고 생각합니다. 😃

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +    private int position = 0;
상태가 계속 변할 수 있기 때문에 불변을 하지 않으셨군요?
그렇다면 어떻게 하면 불변으로 관리할 수 있을 지 생각해보면 좋겠어요! 😉

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +        if (MOVING_FORWARD <= randomValue) {
Car 라는 객체가 완성되고 사용하는 상황에서 만약 전진 조건이 4가 아니라 다른 숫자로 변경 되었을 때, Car 클래스의 내부 로직을 수정하지 않고 요구사항을 변경하는 방법도 생각해보시면 좋겠네요! 😊
그리고 현재 메서드가 랜덤 값을 구하고 이동하는 기능을 담당하고 있는데요, `순수하게 이동만하는 메서드`와 랜덤 값에 대한 로직을 처리한 후 `순수하게 이동만하는 메서드`로 이동을 하는 방식으로 구현해 볼 수 있을 것 같아요. 😉

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +    public boolean isMaxPosition(int maxPosition) {
클래스 내부에서 동등성 비교 👍

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/domain/Cars.java
> +    public static Cars from(List<String> carNames) {
지금 단계에서 DTO 를 사용할 필요는 굳이 없다고 생각해요. 🤔
DTO 를 사용하는 이유는 실제 Domain Model 의 필드 중 일부만 보여주기 위한 용도로 사용한다고 생각합니다. 지금 구현에는 Car 객체를 의미없이 한 번 더 감싸고 있는 형태라고 생각해요.

그래도 Domain Model 과 View의 의존성을 분리해주는 시도는 좋다고 생각합니다.👍

한 가지 궁금한 점은 Cars 객체를 View 에 보낼 때는 DTO 를 사용하시는데, View 에서 Cars 로 보낼 때는 DTO 를 사용하지 않나요? 오히려 최초 입력 받을 때 `자동차 이름 리스트`로 Car 를 생성하기 때문(String name 만 존재)에 입력 로직이 DTO 를 사용하기에 더 적합하다고 느껴져요.
노력님은 이번에 어떤 기준으로 DTO 를 사용한 것인가요?😀


==============================================================================
첫 번째 질문에 대한 답변입니다.

우선 ArrayList 구현체를 사용하기 싫어서 팩토리 메서드로 대체했다? 이건 개념이 잘못 되었다고 생각합니다.
팩토리 메서드에서 사용하고 있는 `Collectors.toList()` 의 내부 구현을 살펴보면 ArrayList 구현체를 사용하고 있습니다. 인터페이스와 구현체의 개념이 헷갈리실텐데, 코딩하면서 점진적으로 학습해나가면 이해하실 수 있을거에요! 💪

![image](https://user-images.githubusercontent.com/49058669/144743940-b56df93b-018b-4f27-ac1a-e8ac3b1cf6b2.png)

추가로 정적 팩토리 메서드 대신 여러 개의 생성자를 만들어서 생성자 오버로딩을 통해 해결할 수 있다고 생각했지만, 현재 상황에서는 List\<Car\> 와 List\<String\> 의 RowType 이 동일한 타입이라 아래와 같이 구현할 경우 동일한 제네릭 타입에 대한 컴파일 오류가 발생하는군요! 😣
```java
    public Cars(List<String> carNames) {
        validateDuplicate(carNames);
        List<Car> cars = carNames.stream()
            .map(Car::new)
            .collect(Collectors.toList());
        this(cars);
    }

    public Cars(List<Car> cars) {
        this.cars = cars;
    }
```
이런 경우에 정적 팩토리 메서드를 통해 해결할 수 있다고 생각합니다. 😁

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/domain/Cars.java
> +        Set<String> nonDuplicateNames = new HashSet<>(carNames);
HashSet 을 통한 중복 검증 👍

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/domain/Cars.java
> +        cars.forEach(Car::move);
```suggestion
        for (Car car : cars) {
            car.move();
        }
```

[Iterable.forEach() 와 for-each 루프의 차이](https://newbedev.com/java-8-iterable-foreach-vs-foreach-loop)에 대해 알아보면 좋겠어요. 🙃

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/domain/Cars.java
> +        return cars.stream()
StreamAPI 를 능숙하게 사용하시는군요!! 👀

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/domain/Cars.java
> +    public List<CarDto> toCarDtos() {
도메인 모델이 DTO 를 알면 어떤 문제가 있을까요? 🙄

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/view/InputView.java
> +        while (!isValidInputCarNames(carNames)) {
조건문에서 검증을 위해 `!` 를 사용하는건 안좋습니다.
실수로 ! 를 놓치고 읽을 수도 있고 가독성 측면에도 좋지않습니다.
해당 메서드 내부에서 `!` 연산을 통해 false 를 반환하는 메서드로 로직을 변경해보는건 어떨까요?

```suggestion
        while (isNotValidInputCarNames(carNames)) {
```

2021-12-05 08:49 UTC, lns13301 commented on src/main/java/racingcar/view/InputView.java
> +        if (carNames.stream().anyMatch(String::isEmpty)) {
```suggestion
        boolean result = tryCount.chars()
            .anyMatch(Character::isLetter);
        if (result) {
```

StreamAPI 가독성 향상을 위해 분리해주는게 좋아보입니다. 😁

2021-12-05 08:49 UTC, lns13301 commented on src/test/java/racingcar/domain/CarTest.java
> +        assertRandomNumberInRangeTest(
이번에 알게 되었는데 랜덤 테스트를 지원해주는 정말 좋은 기능이라고 생각해요. 😁

2021-12-05 08:49 UTC, lns13301 commented on src/test/java/racingcar/domain/CarsTest.java
> +        //assertThat(cars.size()).isEqualTo(2);
두 번째 질문에 대한 답변입니다.

프로덕션 코드에 테스트를 위한 코드를 짜는 것은 좋지 않습니다. 😂
그래도 add, remove, size 같이 개발자가 예상 가능한 메서드는 구현해도 상관없다고 생각합니다.
다른 개발자가 노력님이 만든 클래스를 사용하는 상황을 생각해 봅시다.
해당 클래스를 사용하다가 크기비교가 필요한 경우에`cars.size()` 라는 "메서드가 있을까?" 라고 생각하고 확인해 보고, 해당 메서드가 있으면 "사이즈를 바로 알아낼 수 있겠네?" 라고 생각하고 편하게 사용할 수 있겠죠? 컬렉션에 값을 추가해야할 때, `add()` 라는 메서드가 있는지 확인해보신 경험이 있으실거에요. 이런 상황 때문에 메서드 이름을 컨벤션에 맞춰 직관적으로 네이밍할 필요가 있습니다.
만약 Car 클래스에 `getPositionForTest()` 라는 메서드가 public 으로 존재한다면 사용자는 이 메서드는 무슨 메서드인지 혼동이 올 것입니다.
무슨 메서드인지 어디에 사용하는 메서드인지 모르기 때문에 클래스 파일에 들어와서 메서드가 어떻게 구현되었는 지 로직을 확인해야 하는 상황이 발생해요. 따라서 클래스를 설계할 때는 `기능 동작을 위한 메서드` 혹은 `개발자가 예측가능한 네이밍과 기능의 메서드`만 구현해두시는게 좋습니다.

그리고 현재 구현되어있는 기능으로만 size 테스트를 구현할 경우는 아래와 같이 구현할 수 있겠네요. 👍

```suggestion
        assertThat(cars.findWinnerCarNames()).hasSize(2);
```

사용하지 않는 주석은 제거해주세요! 😉

2021-12-05 08:49 UTC, lns13301 commented on src/test/java/racingcar/domain/CarsTest.java
> +    private static final int MOVING_FORWARD = 4;
테스트 코드를 만들다니 아주 좋습니다! 💯

2021-12-05 17:24 UTC, yuminhwan commented on docs/README.md
> +## 🔥 구현할 기능 목록
감사합니다 😂

2021-12-05 17:31 UTC, yuminhwan commented on src/main/java/racingcar/domain/Car.java
> +    private static final String ERROR_WHITE_SPACE_NAME = "[ERROR] 공백인 이름은 입력할 수 없습니다. 다시 입력해주세요.";
그저 구현하기 편하도록 메시지 같은 것도 일단 상수로 만들고 사용해야지 라는 생각을 한 것 같습니다. 
그러다 보니 상수에 대한 개념이 옅어진 것? 같습니다.
중복 사용이나 의미를 파악할 수 없을 때만 사용하도록 노력하겠습니다. 

- 그렇다면 `,`와 같은 구분자도 상수로 추출할 필요가 없을까요?

2021-12-05 17:33 UTC, yuminhwan commented on src/main/java/racingcar/domain/Car.java
> +        if (name.length() > 5) {
매직넘버를 피하기 위한 상수 사용을 생각해도 아직 손에 익지 못한 듯 하네요.😓
좀 더 꼼꼼히 보는 습관을 길러야 할 것 같습니다...

2021-12-05 17:40 UTC, yuminhwan commented on src/main/java/racingcar/domain/Car.java
> +    private int position = 0;
미션 요구사항에 Car 객체에 대한 요구사항이 있어 이런 식으로 구현하였습니다. 
불변으로 관리하기 위해서는 외부에서 주입하는 방식 구현 하면 될것 같은데
정답일지는 모르겠네요😂

2021-12-05 17:48 UTC, yuminhwan commented on src/main/java/racingcar/domain/Car.java
> +        if (MOVING_FORWARD <= randomValue) {
메소드가 두가지 일을 하고 있군요 미처 생각도 못한 것 같습니다. 
내부 로직을 수정하지 않고 변경하는 방법은 랜덤 값에 대한 로직을 처리하는 메소드를 다른 객체에게 책임을 주는 방식? 으로 해결 될 수 도 있을 것 같습니다.

2021-12-05 17:49 UTC, yuminhwan commented on src/main/java/racingcar/domain/Car.java
> +    public boolean isMaxPosition(int maxPosition) {
감사합니다!😄

2021-12-05 18:12 UTC, yuminhwan commented on src/main/java/racingcar/domain/Cars.java
> +    public static Cars from(List<String> carNames) {
말씀하신대로 `Domain Model` 과 `View`의 의존성을 분리해주기 위해 `DTO`를 사용하였습니다. 
해당 미션에서는 필요없더라도 분리하는 연습을 하고 싶어 이런 식으로 구현했습니다.

`InputView`에서 `Cars`로 보낼 때 `DTO`사용은 생각도 못했네요.😂
그저 `List<String>`만 주면 되겠지 라고 생각한 것 같습니다. 
`DTO`에 대해 더욱 공부해봐야겠습니다!!

2021-12-05 18:35 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +    private static final String ERROR_WHITE_SPACE_NAME = "[ERROR] 공백인 이름은 입력할 수 없습니다. 다시 입력해주세요.";
제가 프로그래밍 하는 방식을 말씀드린거에요. 노력님이 생각할 때 상수로 처리하는게 편하시면 그렇게 하셔도 무관하다고 생각합니다.
구분자의 경우는 의미를 파악하기 힘든 매직넘버라고 생각되기 때문에 상수로 관리하는게 좋다고 생각합니다.
제가 상수로 사용하지 않는 값은 한 곳에서만 사용하는 메시지 혹은 값이 0 일 때는 상수로 사용하고 있지 않아요. 😉

2021-12-05 18:36 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +        if (name.length() > 5) {
자연스러운 겁니다. 저도 이랬어요! 😂😂

2021-12-05 18:36 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +    private int position = 0;
한번 생각해보면 좋을 것 같아서 남겨드린 코멘트에요. 이렇게 구현하시면 됩니다!

2021-12-05 18:37 UTC, yuminhwan commented on src/main/java/racingcar/domain/Cars.java
> +    public static Cars from(List<String> carNames) {
`인터페이스`와 `구현체` 개념 자체를 잘못 이해하고 있었네요 ㅠㅠ 
결국 `Collectors.toList()`도 `ArrayList` 구현체를 사용하고 있었다니 처음 안 사실입니다...
더욱 학습해봐야겠습니다. 

- 질문 
    - 그렇다면 생성자에 `자동차 이름 리스트`을 `자동차 객체 리스트`로 바꾸는 로직을 넣는 것은 안 되니?? 정적 메소드 팩토리를 통해 구현했다고 생각하면 될까요??
    - 위 질문에 이어서 생성자에 별도의 로직을 넣는 것은 안 좋나요?
    - ex) `String` -> `int`로 바꿔주기 위해 `Integer.parseInt` 를 사용함. 
    - `주 생성자에는 제공되는 인자들이 완전해야한다.` 이 말을 지키기 위해 정적 메서드 팩토리를 사용하면 될까요?

2021-12-05 18:39 UTC, yuminhwan commented on src/main/java/racingcar/domain/Car.java
> +    private int position = 0;
불변으로 관리하기 위해서는 주입하는 방식이 맞을까요??
늦은 시간에 저 때문에 깨신 게 아닐지 걱정되네요 😭

2021-12-05 18:39 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +        if (MOVING_FORWARD <= randomValue) {
자동차 이동로직을 boolean 으로 구현하고 이동 여부를 외부에서 주입하는 방법을 사용할 수 있겠네요. 이와 관련해서 디자인 패턴 중 하나인 `상태 패턴`을 알아보시면 참고 되실거에요! 😊

2021-12-05 18:53 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +    public boolean isMaxPosition(int maxPosition) {
무분별한 getter 를 사용하는 경우를 생각하기 어렵다고 느끼시는군요? 저도 공감합니다. 🤯
무분별하게 사용하지 말라는 것이지 getter 를 사용하지 말란 뜻은 아닙니다. 😉
로직을 구현할 때 `과연 getter 를 사용해야 구현할 수 있는 로직인가?` 에 대해서 고민해보시면 된다고 생각합니다.
최대 이동거리가 얼마인지에 대해서는 결국 최대 값을 구하기 위해 여러 값이 필요하기 때문에 getter 를 사용해야 합니다.

그러면 무분별하게 getter 를 사용하는 예시를 확인해보겠습니다.
아래의 로직을 무분별하게 getter 를 사용한 경우라고 볼 수 있습니다.
```java
    public List<String> findWinnerCarNames() {
        int maxPosition = findMaxPosition();
        return cars.stream()
            .filter(car -> car.getPosition() == maxPosition)
            .map(Car::getName)
            .collect(Collectors.toList());
    }
```
객체의 책임, 캡슐화 등에 대해서도 학습하면 도움이 됩니다!
`객체에 메시지를 던져라!` 라는 말을 새겨두고 구현하면 덜 헷갈릴거 같습니다. 😊

2021-12-05 19:14 UTC, lns13301 commented on src/main/java/racingcar/domain/Cars.java
> +    public static Cars from(List<String> carNames) {
## 질문
### 그렇다면 생성자에 자동차 이름 리스트을 자동차 객체 리스트로 바꾸는 로직을 넣는 것은 안 되니?? 정적 메소드 팩토리를 통해 구현했다고 생각하면 될까요??
[이 글](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)을 참고해보면 4번에 가깝게 사용한다고 볼 수 있겠네요.
조금 더 상세하게 설명드려볼게요.
```java
    public Cars(List<String> carNames) {
        validateDuplicate(carNames);
        List<Car> cars = carNames.stream()
            .map(Car::new)
            .collect(Collectors.toList());
        this(cars);
    }

    public Cars(List<Car> cars) {
        this.cars = cars;
    }
```
위의 예시를 살펴보면 하나는 String 타입의 리스트고 다른 하나는 Car 타입의 리스트인데 왜 런타임 상에서 오류가 날까요?
바로 List 의 실제 구현은 T 라는 제네릭 타입을 받을 수 있도록 구현되어 있습니다. 따라서 런타임 시점에 타입이 결정되기 때문에 위의 코드는 사실상 아래와 같은 상태입니다.

```java
    public Cars(List<T> cars) {
        validateDuplicate(carNames);
        List<Car> cars = carNames.stream()
            .map(Car::new)
            .collect(Collectors.toList());
        this(cars);
    }

    public Cars(List<T> cars) {
        this.cars = cars;
    }
```
따라서 온전한 생성자를 만들어둔 다음 List\<String\> 의 자동차 이름으로 객체를 생성하고 싶다면 정적 팩토리 메서드를 사용해야 한다고 생각합니다.
또한 또 다른 List\<T\> 를 사용한 파라미터로 객체를 생성할 때 정적 팩토리 메서드를 사용하면, 메서드 이름을 다르게 지어서 위와 같은 상황을 피할 수 있습니다.

### 위 질문에 이어서 생성자에 별도의 로직을 넣는 것은 안 좋나요?
복잡한 로직이 들어가는 것이 좋지는 않겠죠?
생성자에서 해야할 일 정도는 할 수 있다고 생각합니다. 아래처럼 구현할 수 있는지 궁금하신 것 같아요.
```java
    private Cars(List<String> carNames) {
        validate(carNames);
        this.cars = convertCarNamesToCars(carNames);
    }
```
이렇게 구현하셔도 상관없습니다. 검증과 생성에 대한 로직은 포함해도 된다고 생각해요.

### 주 생성자에는 제공되는 인자들이 완전해야한다. 이 말을 지키기 위해 정적 메서드 팩토리를 사용하면 될까요?
[이 글](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)에서 나온 네 가지 장점을 바탕으로 사용에 적합한 지 판단할 수 있을거라고 생각합니다. 👍

2021-12-05 19:18 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +    private int position = 0;
불변으로 관리하면 객체를 매번 새로 만들어줘야겠죠?
그렇게 되면 주 생성자를 통해 자동차의 이름과 위치를 입력받아서 새로 객체를 만들어줘야 할 것입니다.

2021-12-05 19:25 UTC, yuminhwan commented on src/main/java/racingcar/domain/Cars.java
> +        Set<String> nonDuplicateNames = new HashSet<>(carNames);
감사합니다 😂

2021-12-05 19:29 UTC, yuminhwan commented on src/main/java/racingcar/domain/Cars.java
> +        cars.forEach(Car::move);
말씀하신 링크가 영어라 잘 와닿지가 않아 검색해보았더니 
https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/
이런 글이 나왔습니다. 
스트림의 forEach 구문과 For-each 루프에 대한 내용이지만 동일하다고 봐도 될까요?

2021-12-05 19:30 UTC, yuminhwan commented on src/main/java/racingcar/domain/Cars.java
> +        return cars.stream()
이번에 StreamAPI를 써봤더니 더욱 가독성있는 코드가 만들어진 것 같습니다. 
아직 학습해야할 것이 많이 있지만요 😂

2021-12-05 19:33 UTC, yuminhwan commented on src/main/java/racingcar/domain/Cars.java
> +    public List<CarDto> toCarDtos() {
DTO가 변하면 도메인 모델도 변해야 하는 문제가 생길 것 같습니다. 

- 질문 
   - 현재 일급컬렉션을 사용하여 구현하였습니다.
   - 말씀하신대로 도메인 모델이 DTO를 모르게 구현하려면 `getter`를 이용하여 `cars`를 반환해 `Application`쪽에서 `DTO`로 매핑 시켜야 하는 데 이 방법이 맞을까요??

2021-12-05 19:34 UTC, yuminhwan commented on src/main/java/racingcar/view/InputView.java
> +        while (!isValidInputCarNames(carNames)) {
`!`을 지양하도록 해야겠군요! 
좋은 말씀 감사합니다!!

2021-12-05 19:35 UTC, yuminhwan commented on src/main/java/racingcar/view/InputView.java
> +        if (carNames.stream().anyMatch(String::isEmpty)) {
아직 StreamAPI가 익숙하지 않은 것 같습니다. 
가독성을 위해 말씀하신 방식처럼 구현하도록 노력해야겠습니다.

2021-12-05 19:37 UTC, yuminhwan commented on src/test/java/racingcar/domain/CarTest.java
> +        assertRandomNumberInRangeTest(
요구한 테스트코드를 보니 있어서 가져와서 써봤습니다. 
이것때문에 랜덤값을 만들어주는 함수를 제공한 것 같습니다.

2021-12-05 19:41 UTC, yuminhwan commented on src/test/java/racingcar/domain/CarsTest.java
> +        //assertThat(cars.size()).isEqualTo(2);
처음 구현할 때 필요없는 메서드라도 `개발자가 예측가능한 네이밍과 기능의 메서드`라면 구현해도 되는 군요! 
테스트코드를 작성하면서 필요한 메서드를 구현하고 다시 지우고 할 필요가 없겠네요!! 
큰 가르침을 얻은 것 같습니다. 
감사드립니다!!

2021-12-05 19:41 UTC, yuminhwan commented on src/test/java/racingcar/domain/CarsTest.java
> +    private static final int MOVING_FORWARD = 4;
아직 많이 부족한 걸 느낍니다. 
더욱 열심히 해봐야겠습니다.👍

2021-12-05 19:45 UTC, lns13301 commented on src/main/java/racingcar/domain/Cars.java
> +        cars.forEach(Car::move);
네, 동일하다고 생각하고 보셔도 큰 문제 없을 것 같아요! 👍

2021-12-05 19:53 UTC, lns13301 commented on src/main/java/racingcar/domain/Cars.java
> +    public List<CarDto> toCarDtos() {
네, 질문에 적으신 방법으로 구현하면 되겠네요. 👍

2021-12-12 10:33 UTC, yuminhwan commented
안녕하세요 와일더님.
꼼꼼히 리뷰를 남겨주신 점 감사드립니다. 😂
또한, 늦은 시간 코멘트를 남겨서 죄송합니다.😭
말씀하신 대로 수정을 해보았는 데 염치없지만 몇가지 더 질문하려고 합니다 😓

## 1. 자동차 이름 리스트 DTO 관련 
- 현재 View에서 자동차 이름을 입력받아 `CarNameDto` 리스트로 반환해주고 있습니다. 
    - 이런 경우 불가피하게 `Cars` 객체의 정적 팩토리 메서드에서 `CarNameDto` 알 수 밖에 없습니다. 
    - 이럴 땐 `Application` 쪽에서 `CarNameDto`를 통해 `Car` 객체를 받은 뒤 `Cars`에 주입해줘야 하는 것일까요??
- 위 질문에 이어 Cars의 `findWinnerCarNames` 메서드를 통해  우승자 이름을 반환하고 있습니다. 
    - 이럴 경우 `DTO`를 쓴다면 `Car` 객체 자체를 반환한 뒤 `Application`쪽에서 Dto로 매핑시켜야 할까요??

## 2. 테스트 관련 
- Cars 객체의 findMaxPosition 메서드를 테스트하기 위해 isCarsMaxPosition 테스트메서드를 구현하였습니다. 
    - 이런 경우 불가피하게  findMaxPosition 메서드를 public으로 설정해야하는 데 이 메서드가 결국 Cars에서 밖에 쓰이지 않아 private로 설정해야 할 것 같습니다. 
    - 이렇게 private로 설정된 기능을 테스트하기 위해서는 어떻게 코드를 짜야하는 건가요?

질문이 많아서 죄송합니다😂 이해가 되실지는 모르겠네요....
아직 더 공부해야 할 것이 많은 것을 느낍니다...
마지막으로, 다시 한번 감사드립니다!!

2021-12-13 07:51 UTC, lns13301 requested changes
안녕하세요 노력님!
피드백 반영도 잘해주시고 열심히 하는 모습이 너무 좋습니다. 😊

이번 미션을 통해 많은 것을 배우신 것 같아요. 여기서 미션을 종료할 수도 있겠지만, 노력님이 남겨주신 질문에 대한 답변을 남기고나니 약간 다듬을 부분이 보이는군요. 조금만 더 마무리하면 끝날 것 같습니다. 조금만 더 파이팅!!

2021-12-13 07:51 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +        if (movableStrategy.isMovable()) {
전략패턴을 적용해보셨군요! 👍

질문을 하나 드려봅니다.
이동 전략을 Car 객체 내부에서 가지고 있는 방식과 move 메서드를 실행할 때 주입받는 방식은 어떤 차이가 있을까요?

2021-12-13 07:51 UTC, lns13301 commented on src/main/java/racingcar/dto/CarNameDto.java
> +    private final String name;
1. 자동차 이름 리스트 DTO 관련

좋은 질문입니다. 👍
객체가 DTO 를 알게되면 문제가 되지 않냐는 질문인데요, 이럴땐 두 가지를 생각해볼 수 있어요.
1. 도메인이 DTO 를 알고있다.
2. DTO 가 도메인을 알고있다.
두 가지 방법 중 하나를 선택하여 해결해야 합니다. 저는 보통 DTO 에서 도메인으로 변경해주는 로직정도는 만들어서 사용하고 있습니다.
```java
    public Car toEntity() {
        return new Car(name, position);
    }
```
개인마다 의견이 다를 수 있으니 노력님이 맞다고 생각하는 방향으로 구현하시면 되겠습니다. 😉

2021-12-13 07:51 UTC, lns13301 commented on src/main/java/racingcar/domain/Cars.java
> +        validateDuplicate(carNames);
3. 입력 Exception 부분

객체 내부에서 발생하는 예외처리를 어떻게 해야하나 질문 하셨군요.
미션 요구사항이 어떻게 되어있나요? `프로그램의 예외가 발생 시 재입력 받도록 한다.` 처럼 요구사항이 적혀있다면 이에 맞게 while 을 통해 재입력 받도록 구현해야 합니다. 위의 조건이 없다면 개인 취향에 맞게 재입력 받거나 프로그램을 예외 메시지와 함께 종료시키는 방법 중에 선택하여 구현하면 되겠습니다. 😁

2021-12-13 07:51 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +    public boolean isMaxPosition(int maxPosition) {
2. 테스트 관련

해당 메서드는 현재 Cars 객체의 `findWinnerCarNames()` 메서드에서 이미 사용중이기 때문에 public 으로 두어도 될 것 같아요. 만약 private 으로 둬야하는 메서드의 단위 테스트를 꼭 해야하는 경우에는 `JUnit private 메서드 테스트하기`를 찾아보고 해보시면 되겠어요. 😉

2021-12-16 15:42 UTC, yuminhwan commented on src/main/java/racingcar/domain/Car.java
> +        if (movableStrategy.isMovable()) {
Car객체 내부에서 가지고 있는 방식의 경우 객체가 생성되었을 때 수정이 불가능할 것 같고 
주입받는 경우 실행될때마다 다른 전략을 주입할 수 있을 것 같습니다. 
추가적으로, 메서드가 실행할 때 주입받는 방식으로 구현하게 되면 테스트도 용이해질 것 같습니다.

2021-12-16 15:44 UTC, yuminhwan commented on src/main/java/racingcar/dto/CarNameDto.java
> +    private final String name;
DTO가 도메인을 알고 있는 쪽이 더욱 좋은 방법일 것 같습니다. 
그렇다면 현재 Cars가 CarNameDto의 name을 꺼내서 Car객체로 바꿔주는 것이 아닌 Application 쪽에서 CarNameDto를 Car 객체로 바꾸준 다음 Cars에 주입해주는 것이 맞는 방향인가요?

2021-12-16 15:52 UTC, yuminhwan commented on src/main/java/racingcar/domain/Cars.java
> +        validateDuplicate(carNames);
현재는 InputView에서 입력값을 검증한 뒤 맞지 않는다면 재입력을 받도록 하였습니다. 
하지만 View에서 입력값 검증한다고 도메인에서 유효성 검사를 안하면 안되니 View에서 입력값을 검증하여 재입력을 받는 것 보단 도메인을 생성할 때 예외가 발생한다면 재입력을 받도록 하는 것이 맞다고 생각합니다.  
이런 경우 아래와 같은 방법으로 재입력을 받도록 구현하면 될까요? ( 이 코드는 다음 미션의 코드를 가져왔습니다! ) 
```
    private Coins registerMachineMoney() {
        wrongInput = true;
        Coins coins = null;
        while (wrongInput) {
            try {
                int vendingMachineMoney = InputView.inputVendingMachineMoney();
                coins = new Coins(vendingMachineMoney);
                OutputView.printVendingMachineCoins(coins.getCoins());
                wrongInput = false;
            } catch (IllegalArgumentException e) {
                OutputView.printErrorMessage(e.getMessage());
            }
        }
        return coins;
    }
```

2021-12-16 15:56 UTC, yuminhwan commented on src/main/java/racingcar/domain/Car.java
> +    public boolean isMaxPosition(int maxPosition) {
메서드의 접근 제한자를 다른 곳에서 쓰지 않는 다면 private로 설정하였는 데 다른 곳에서 쓰이지 않는 메서드라도 public으로 열어두어도 큰 상관이 없나요? 
`Junit private 메서드 테스트하기` 방법을 알려주셔서 감사합니다 !!

2021-12-17 14:35 UTC, lns13301 commented on src/main/java/racingcar/dto/CarNameDto.java
> +    private final String name;
DTO 는 데이터를 포장하여 전달하기 위한 용도로 사용합니다. 그렇다면 꼭 CarDTO 를 사용해야할까요? CarsDTO 를 사용하면 되지 않을까요? 🤔

2021-12-17 14:37 UTC, lns13301 commented on src/main/java/racingcar/domain/Cars.java
> +        validateDuplicate(carNames);
두 곳에서 모두 검증을 하는건 어떨까요? 🤔
일반적으로 프론트측에서도 검증을 한 후 데이터를 넘겨주지만 도메인에서 한 번 더 검증하듯 말이죠! 😀

2021-12-17 14:39 UTC, lns13301 commented on src/main/java/racingcar/domain/Car.java
> +    public boolean isMaxPosition(int maxPosition) {
설계를 할 때, 해당 메서드 내부에서만 사용되는 용도로 설계된 메서드라면 private 으로 접근제어자를 두는 것이 맞다고 생각합니다. 만약 다른 메서드에서 사용할 수 있을만한 메서드 `size()`, `isTrue()` 같은 메서드라면 public 으로 두어도 괜찮다고 생각하지만, 되도록 private 으로 두는 것을 선호합니다. 👍

2021-12-17 18:37 UTC, yuminhwan commented on src/main/java/racingcar/domain/Cars.java
> +        validateDuplicate(carNames);
의견 감사드립니다!!

2021-12-17 18:37 UTC, yuminhwan commented on src/main/java/racingcar/domain/Car.java
> +    public boolean isMaxPosition(int maxPosition) {
감사합니다!!

2021-12-17 19:38 UTC, yuminhwan commented
안녕하세요 와일더님.
재리뷰를 드렸음에도 꼼꼼히 리뷰를 남겨주신 점 감사드립니다. 😂
말씀해주신거처럼 수정을 해보았는데 원하시는 대로 수정이 되었는 지는 잘 모르겠습니다...😭
다시 한번 따끔한 충고 부탁드립니다!!
( 추가적으로, position을 원시값 포장 해보았습니다! )

2021-12-18 03:48 UTC, lns13301 approved these changes
안녕하세요 노력님! 😊

노력님이 노력하시는 모습을 보고, 제가 생각한 것보다 훨씬 많은 리뷰를 드리게 되었어요.. 😂
이번 미션을 통해 새롭게 학습한 내용은 실제 우아한테크코스 레벨1 과정에서 학습하는 내용의 절반 이상에 해당하는 내용을 학습하셨다고 봐도 될 정도로 정말 많은 내용이었거든요.. 😭
그런데 그 많은 리뷰를 다 흡수하고 코드에 적용해나가는 모습을 보니 정말 흐뭇해집니다. 😁
마지막으로 전체적으로 코드를 다시 한번 훑어보듯이 살펴보았는데요, 설계가 굉장히 깔끔하고 굳이 손대야 할 곳을 찾지 못했습니다. 💯👏👏👏

많은 리뷰를 반영하느라 정말 정말 고생 많으셨습니다. 이번 미션에서 배우신 내용을 그대로 흡수하신다면 앞으로 코드를 설계해나갈 때 정말 좋은 설계를 하실 수 있을 거로 생각합니다. 😉

지금까지 자동차 경주 미션 하느라 고생 많으셨습니다.!! 👏👏👏

2021-12-18 03:48 UTC, merged

2021-12-20 12:34 UTC, yuminhwan commented
안녕하세요 와일더(@lns13301)님! 
많이 부족한 코드였지만 꼼꼼히 리뷰 남겨주신 점 정말 감사드립니다! 😄
코드리뷰가 거듭되면서 배워야 할 점이나 생각해야 할 점 등 정말 많이 배운 것 같습니다. 
말씀하신대로 앞으로도 이번에 배운 점을 생각하며 설계해 나가도록 하겠습니다!! 

지금까지 못난 코드 봐주시느라 고생 많으셨고 감사했습니다!! 😭