[자동차 경주 게임] 오리 미션 제출합니다.
REVENGE-WOOTECO/java-racingcar-precourse pull request #3
Opened 2021-12-06 13:01 UTC by bbeomgeun

안녕하세요. 1주차 코드 리뷰를 진행하면서 많은 것을 배웠습니다! 
이번 2주차 과제는 일부러 1주차 때 습득한 지식들을 사용해서 코드를 작성해봤습니다..!

스트림을 연습해보고, 접근제한자를 신경쓰고, MVC 구조를 시도해보고, 일급컬렉션이나 원시타입 입력값을 VO로 감싸는 것 등 1주차 리뷰때 배운 걸 사용해봤는데 보시고 따끔한 리뷰 부탁드립니다!!

---
Q. InputView나 OutputView 클래스에서 단순 출력이나 입력은 static을 통해서 인스턴스를 생성하지 않아도 메서드를 사용할 수 있게 구현해봤는데요. 출력 메서드 중 내부적으로 다른 클래스를 받아서 로직을 작성해야 하는 경우는 static 메서드를 제외했습니다. (static 메서드 안에 인스턴스 변수를 사용할 수 없다 를 생각하고 제외했습니다)
이런 경우는 결국 outputView의 객체를 생성한 다음, 메서드를 호출해야 하는데 이렇게 어떤 메서드에는 static이 쓰이고, 안 쓰이고 혼합되게 구성해도 되는지 궁금합니다!

2021-12-08 08:39 UTC, Be-poz requested changes
안녕하세요 오리 우테코 3기 파즈라고 합니다.  
코드 잘 확인했습니다. 코멘트를 달아놨으니 확인해주세요! 궁금한 점이 생기시면 그냥 물어보시면 됩니다! 감사합니다.

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/view/InputView.java
> +    public static String input() {
static 메서드로만 이용하실거면 기본 생성자의 접근제어자를 private으로 두면 좋을 것 같아요

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/Car.java
> +        return isValidSize(name);
생성자에서 ``isValidInput`` 호출 후에 이 메서드에서 별도의 작업없이 ``isValidSize`` 메서드를 호출하고 있는데요,  
그러면 그냥 ``isValidInput`` 에다가 ``isValidSize``의 로직을 넣거나 아니면 생성자에서 바로 ``isValidSize`` 를 호출하면 되지 않을까요? 나누신 이유가 있을까요?

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/Car.java
> +        }
생성자 우측에 ``throws IllegalArgumentException``을 따로 붙이신 이유가 있을까요?  
생성자에서 현재 throw를 던져주고 있는데, ``validateInput(name)`` 메서드를 두고 내부에서 검증 후에 예외를 던지는 것은 어떻게 생각하시나요 ??

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/Car.java
> +        if (movingCondition()) {
``movingCondition``는 boolean return을 하는 메서드같은 네이밍이 아닌데, ``isMovingCondition``는 어떨까요?

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/Car.java
> +    public void movingForward() {
``movingForward``-> ``moveForward`` 여야 동사의 의미가 될 것 같아요!

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/Cars.java
> +                .collect(Collectors.toList());
```suggestion
        this.carList = Arrays.stream(carStr.split(","))
                .map(Car::new)
                .collect(Collectors.toList());
```
주요 stream 체이닝에 개행을 해주면 가독성이 더 올라갈 것 같습니다.

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/Cars.java
> +        return this.carList;
기존의 Cars에 car1, car2가 담겨있는 상황이라고 가정을 해볼게요.  
caller가 getCurrentCars를 호출해서 List<Car>를 받았습니다.  
Cars에 car3가 추가되었습니다.  

이 때에 caller가 가지고 있는 List<Car>에는 car3이 추가될까요 추가되지 않을까요?

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/Cars.java
> +    private int getFinalMaxPosition() {
``getWinnersName()`` -> ``getFinalMaxPosition``의 순서로 호출이 되고 있습니다.  
이 경우에는 해당 메서드가 ``getWinnersName()`` 메서드 하단에 위치하면 코드 가독성이 더 올라갈 수 있을 것 같습니다.

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/Cars.java
> +        return carList.stream().filter(v -> v.getFinalPosition() == winnerPosition)
v가 아니라 car로 두면 더 이해하기 편할 것 같습니다.  
``v.getFinalPosition() == winnerPosition``을 Car 객체한테 물어보는 식으로 변경하면 좋을 것 같습니다.

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/Cars.java
> +        Optional<Car> winner = carList.stream().max(comparatorByPosition);
``comparatorByPosition``은 인라인 변수로 두어도 될 것 같습니다.

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/Cars.java
> +        Optional<Car> winner = carList.stream().max(comparatorByPosition);
``Optional``이 왜 나올까요 ?? return에서 ``winner.get()``으로 바로 사용을 하고있는데 적절한 처리법은 어떤 방법이 있을까요?

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/model/IterationCount.java
> +        if (!isNumber(iterationCount)) {
Car에서 작성했던 리뷰와 동일한 리뷰 남겨드리고 싶습니다.

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/controller/GameController.java
> +        boolean validFlag = true;
``inputNameStr()``에는 따로 명시를 안해주셨는데 이곳에서는 해주셨습니다. 별도의 이유가 있을까요?

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/view/OutputView.java
> +public class OutputView {
InputView는 간단히 ``input``이라는 메서드 하나로 처리해두셨습니다.  
OutputView는 따로 이곳에서 메세지를 관리하고 출력별 메서드를 다 별개로 두신 것은 어떤 생각을 가지고 하신지 궁금합니다.  

답은 없습니다! OutputView가 오직 이 자동차 경주 게임을 위한 OutputView고 확장을 고려하지 않았다면 다음과 같은 방법으로 진행을 해도 이상이 없을 것입니다. 만약 다른 게임이 추가가 되고 해당 게임에서도 고유의 message들이 있다고 할 때에, 현재와 같은 클래스라면 모든 message들을 OutputView에 상수로 추가하는 방식으로 진행하게 되겠죠. 과연 이러한 방식이 맞을까요? 생각을 듣고 싶습니다.

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/view/OutputView.java
> +    public void printProgress(Cars carList) {
이 메서드와 밑의 메서드는 static을 두지 않으셨는데 이유가 있을까요?

2021-12-08 08:39 UTC, Be-poz commented on src/main/java/racingcar/controller/GameController.java
> +        while (true) {
validFlag를 이용할 수 있지 않을까요??

2021-12-08 08:39 UTC, Be-poz commented on README.md
> +  - [x] 자동차 이름 또는 반복 숫자 입력 받기.
현재 공백까지 이름으로 카운트가 되고 있습니다.  
![image](https://user-images.githubusercontent.com/45073750/145175679-7bd7f5fc-1c8e-4415-8a32-635c0296e291.png)
![image](https://user-images.githubusercontent.com/45073750/145175923-bc2814c0-5956-4475-94ef-ee696e3016e3.png)

+) 시간이 나신다면 중복이름에 대해서도 막을 수 있다면 좋을 것 같습니다.

2021-12-09 12:24 UTC, bbeomgeun commented on src/main/java/racingcar/view/InputView.java
> +    public static String input() {
기본 생성자를 생성해서, 외부에서 객체 생성을 방지하기 위해서 private으로 막아두라는 말씀이시죠??

2021-12-09 12:26 UTC, bbeomgeun commented on src/main/java/racingcar/model/Car.java
> +        return isValidSize(name);
아, 이건 제가 놓친 부분인 것 같습니다..
검증을 추가로 진행해서 isValidInput 메서드로 묶으려고 했는데 그대로 지나친 것 같아요..

2021-12-09 12:32 UTC, bbeomgeun commented on src/main/java/racingcar/model/Car.java
> +        }
1. 제가 생각한 것은 예외를 throw로 발생시키만 하고 여기서 처리하지 않으므로, throws로 책임을 넘겨주기 위해서 throws를 했습니다.
예상한 프로세스는
GameController에서 입력받고, cars 생성자 호출
cars생성자 내에서 car 객체를 생성하므로 만약 예외상황이 일어나면 예외 발생
throws로 던져줘서

```
   private void inputNameStr() {
        boolean validFlag;
        while (true) {
            try {
                validFlag = true;
                OutputView.printStartMessage();
                cars = new Cars(InputView.input());
            } catch (IllegalArgumentException exception) {
                OutputView.printErrorMessage(exception);
                validFlag = false;
            }
            if (validFlag) {
                return;
            }
        }
    }
```
여기서 예외를 catch 해주는 것으로 생각했습니다. 이렇게 throws를 사용하는 게 아닌가요..?

2. https://github.com/REVENGE-WOOTECO/java-baseball-precourse/pull/6#discussion_r760728011
이 리뷰를 보고 비즈니스 객체 내의 생성자에서 검증을 시도해봤습니다. 
혹시 말씀하시는게 throw를 생성자에서 하지 말고, isValidInput(name) 메서드 내에서 예외를 발생시키라는 말씀이신가요??

2021-12-09 12:33 UTC, bbeomgeun commented on src/main/java/racingcar/model/Car.java
> +        if (movingCondition()) {
넵! 메서드명을 좀 더 이해하기 쉽게 바꾸겠습니다!!

2021-12-09 12:34 UTC, bbeomgeun commented on src/main/java/racingcar/model/Car.java
> +    public void movingForward() {
아 넵, 이것도 너무 생각 없이 네이밍한 것 같습니다 ㅜ

2021-12-09 12:35 UTC, bbeomgeun commented on src/main/java/racingcar/model/Cars.java
> +                .collect(Collectors.toList());
넵, "stream 체이닝에 개행하기"
사실, 이번 2차 과제를 하면서 stream API를 처음 사용해봐서 어디서 개행을 해야할지 헷갈렸습니다..!

2021-12-09 12:47 UTC, bbeomgeun commented on src/main/java/racingcar/model/Cars.java
> +        return this.carList;
음, 제가 Cars의 멤버 변수 carList에 final 키워드를 걸어뒀기 때문에 새롭게 리스트에 추가되면, 새로운 객체가 생성될 것 같습니다.
결론은 기존 list에는 추가되지 않고 새로운 객체가 생성된다..?

혹시 이걸 의도하신게 맞을까요??

2021-12-09 12:48 UTC, bbeomgeun commented on src/main/java/racingcar/model/Cars.java
> +    private int getFinalMaxPosition() {
넵! 코드 호출되는 순서로 작성하기

2021-12-09 12:50 UTC, bbeomgeun commented on src/main/java/racingcar/model/Cars.java
> +        return carList.stream().filter(v -> v.getFinalPosition() == winnerPosition)
넵! 변수 의미 명확하게

2021-12-09 12:55 UTC, bbeomgeun commented on src/main/java/racingcar/model/Cars.java
> +        Optional<Car> winner = carList.stream().max(comparatorByPosition);
stream().max()의 리턴값이 Optional이더라구요. 
Optional 키워드는 NULL을 방지하는 키워드로 알고 있습니다. 

음, 리턴 변수를 Optional로 할당해주지 말고 
`return carList.stream().max(comparatorByPosition).get().getFinalPosition();`
으로 바로 리턴해버리는 건 괜찮을까요?

2021-12-09 12:57 UTC, bbeomgeun commented on src/main/java/racingcar/controller/GameController.java
> +        boolean validFlag = true;
boolean validFlag = true와 boolean validFlag; 를 말씀해주시는 거죠?

다음부턴 코드를 더 꼼꼼히 보겠습니다. 별 의미 없었습니다..

2021-12-09 13:08 UTC, bbeomgeun commented on src/main/java/racingcar/view/OutputView.java
> +    public void printProgress(Cars carList) {
제가 알기론 "static 키워드를 갖게 되면 처음 클래스 로딩 시 초기화되는데, 해당 초기화 시점에 인스턴스 변수는 아직 할당되지 않았으므로 접근이 불가능하다"라고 생각했습니다.
static 메서드 안에서 인스턴스 변수 접근이 불가능하다. 라는 말을 많이 들었는데 제가 오개념을 갖고 있나요??

2021-12-09 13:10 UTC, bbeomgeun commented on src/main/java/racingcar/controller/GameController.java
> +        while (true) {
아 while안에서 true 조건 대신 validFlag로 제어하는 것을 말씀하시는건가요?

2021-12-09 13:11 UTC, bbeomgeun commented on README.md
> +  - [x] 자동차 이름 또는 반복 숫자 입력 받기.
아 많은 것을 놓치고 있었네요 ㅜㅜ
이름으로 공백 들어오는 경우와, 동일한 이름이 들어오는 경우 체크하기.

2021-12-09 13:23 UTC, bbeomgeun commented on src/main/java/racingcar/view/OutputView.java
> +public class OutputView {
우선, InputView에서의 input은 String을 받으면 내부적으로 입력의 종류에 맞게 가공할 수 있겠다 싶어서 하나의 메서드로 표현했습니다.
그런데, outPutView에서는 확장을 생각하지 않고 최대한 하나의 기능만을 하는 메서드로 분리한다는 생각으로 각 메세지에 대해서 메세지에 해당하는 메서드에 네이밍을 하고 출력을 각각 했습니다.

---

```
    public static void printStartMessage() {
        System.out.println(START_MESSAGE);
    }

    public static void printRequestMessage() {
        System.out.println(REQUEST_COUNT_MESSAGE);
    }

    public static void printErrorMessage(Exception e) {
        System.out.println(e.getMessage());
    }

    public static void printResultMessage() {
        System.out.println(RESULT_MESSAGE);
    }
```

public static void printMessage(String message) {
    System.out.println(message);
}

이렇게 확장을 위한 메서드 사용을 말씀하시는 건가요?
저도 파즈가 리뷰해주신대로 확장성 있는 출력뷰로 리팩토링을 해보고 싶습니다.
근데 여기서 궁금한 점이 생기는데요.
1. 보통 확장을 위한 뷰를 갖고 있으면 메세지 출력 제외하고 게임 로직에 관한 출력을 담당하는 메서드들을 게임 종류마다 다 갖고 있어야 할까요? 아니면 이제 여기서 디자인패턴 같은 걸 (아직 싱글톤밖에 공부를 못했습니다 ㅜ) 사용하면서 각 게임 OutputView는 공통 OutputView를 상속 받아서 내부적으로 메서드를 짜야하는 걸까요?

혹시 확장성 있는 OutputView를 리팩토링하기 위해서 구조에 대한 약간의 힌트를 얻을 수 있을까요?

2021-12-09 13:25 UTC, bbeomgeun commented
혹시 위에서 리뷰해주신 것 제외하고, 전체적인 프로젝트 구조나 내부 구현 로직에서 짚고 넘어가야할 부분은 없을까요??
입력값을 VO로 감싸거나 1급 컬렉션을 저렇게 사용하는 것이 맞나 싶어서 질문 드립니다 :)

2021-12-09 13:38 UTC, Be-poz commented on src/main/java/racingcar/view/InputView.java
> +    public static String input() {
네네!

2021-12-09 13:41 UTC, Be-poz commented on src/main/java/racingcar/model/Car.java
> +        }
1. 아 제 말은 ``public Car(String name) throws IllegalArgumentException`` 여기에서 throw를 명시한 이유에 대해서 물은거였습니다! 보통 unchecked exception은 명시하지 않거든요!  

2. 네! valid 작업을 하는 메서드 내에서 바로 예외를 던지면 되지않냐는 뜻이었습니다~!

2021-12-09 13:47 UTC, Be-poz commented on src/main/java/racingcar/model/Cars.java
> +        return this.carList;
final은 할당에 대해서 불변을 유지하는 것입니다.  
따라서, ``final List<T> list = new ArrayList<>();`` 이 코드는 list 할당에 대한 불변을 유지할 뿐이고 ``list.add(Object)`` 에 대한 불변은 막을 수가 없습니다.  
현재 코드에서는 호출자가 ``getCurrentCars()``를 통해서 list를 받아온다고 하더라도 ``return this.carList;`` 의 코드로 바로 Collection을 return 해주었기 때문에 이후에 Cars 가 가지고 있는 carList에 값이 add 된다면 호출자가 가지고있는 carList에도 영향을 미치게 됩니다. ``Collections.unmodifiablelist`` 등으로 해결할 수 있을 것 같습니다.  

마찬가지로  
```java
Cars{
List<T> list;
public Cars(List list){
  this.list = list;
}
main{
 List<T> carList = new ArrayList<>();
carList.add(1);
Cars cars =  new Cars(carList);
}
```
이렇게 바깥에서 생성자의 인수로 List를 주는 상황에서도 참조를 끊어주지 않는다면 Cars 객체 생성 후에 main에서 carList.add(n)를 하면 Cars의 필드에 존재하는 List에도 영향이 가게됩니다.  

컬렉션의 불변이라는 키워드로 학습해보시면 좋을 것 같습니다.

2021-12-09 13:48 UTC, Be-poz commented on src/main/java/racingcar/model/Cars.java
> +        Optional<Car> winner = carList.stream().max(comparatorByPosition);
null 인 경우에 get()을 호출하게되면 어떤일이 일어나게되는지 학습테스트를 작성해보시면 좋을 것 같습니다! ``orElse``, ``orElseThrow``를 한번 찾아보시면 좋을 것 같습니다.

2021-12-09 14:54 UTC, Be-poz commented on src/main/java/racingcar/view/OutputView.java
> +public class OutputView {
이 경우에는 OutputView에서 하는 일이 print에 대한 일 밖에 없어서 좋은 예시가 되기는 힘들겠지만,  
1. Game 별 맞춤 OutputView를 두고 사용하고, 공통 메서드를 위한 인터페이스를 추출한다.
2. 각 Controller에서 메세지에 대해서 조립을 해주고 OutputView로 넘겨준다. 

정도 생각이 드네요. 현재는 GaemController가 곧 Game 그 자체긴한데 2번의 방식대로 한다면 서비스 로직과 출력에 대한 로직이 섞이게 되므로, Game과 Controller에 대한 로직을 분리시켜서 Controller에서는 출력 메세지 정리나 게임흐름에 대한 템플릿을 나타내주는 역할로 사용하면 될 것 같습니다. 메세지에 대한 상수를 누가 가지고 있냐에 대한 것은 상황마다 달라서 이거는 잘 판단해서 분배하시면 좋을 것 같습니다! 남은 프리코스 미션이나 지난기수의 최종테스트 미션들을 진행하시면서 더 좋은 고민하실 수 있을 것 같습니다!

2021-12-09 15:26 UTC, Be-poz commented on src/main/java/racingcar/view/OutputView.java
> +    public void printProgress(Cars carList) {
메서드 안의 인수의 타입은 해당 타입이 들어와야 한다는 뜻입니다. 약속을 정할 뿐이지 클래스 로딩 시에 해당 인스턴스 변수가 존재해야 한다는 뜻이 아닙니다. 따라서, static을 한다고해서 문제되지는 않습니다~!

2021-12-09 15:27 UTC, Be-poz commented on src/main/java/racingcar/controller/GameController.java
> +        while (true) {
넵! 그러면 while문 내의 불필요한 if문 하나가 생략될 수 있을 것 같네요!

2021-12-09 15:31 UTC, Be-poz commented
프로젝트 구조는 현재 미션을 기준으로 이정도로도 저는 충분하다고 생각합니다!! 👍  
내부 구현 로직 또한 복잡한 로직이 아니기 때문에 괜찮은 것 같습니다. 보통 프리코스의 미션은 내부 구현 로직에 중점을 두는 것이 아니라 객체지향적인 코드를 짜는 것에 고민을 해보아라 라는 취지여서요!  
일급컬렉션 부분은 List에 대해서 코멘트 남긴 것 외에는 괜찮은 것 같습니다.  
입력값을 감싸는 VO는 어떤 것을 말씀하신걸까요?! Car 내부의 String name이나 int position 등을 VO로 따로 뺴려면 뺄 수 있을 것 같습니다! VO를 써야겠다는 기준은 객체 내부에서 해당 필드의 로직이 많거나 할 때에 빼면 될 것 같습니다.

2021-12-10 05:43 UTC, bbeomgeun commented on src/main/java/racingcar/model/Car.java
> +        }
1. 아, 그렇군요!! 1차 과제 리뷰때도 들었던 피드백이네요 ㅜㅜ 그때도 unchecked exception을 왜 throws 하냐고 말씀해주셨는데 이번 리뷰를 통해 이제서야 이해하는 것 같네요..
"unchecked는 명시적으로 throws를 해주지 않더라도, 나중에 필요하면 try catch로 핸들링만 하면 된다"로 이해했는데 맞을까요?
checked exception은 exception 핸들링이 코드단에서 강제되구요.

2. 넵. valid 메서드 내부로 한번 숨겨보겠습니다! 그러면 생성자에서는 valid조건문을 통과하지 않으면 그냥 리턴으로 종료시켜주면 되는걸까요?

2021-12-10 05:46 UTC, bbeomgeun commented on src/main/java/racingcar/model/Cars.java
> +        return this.carList;
좋은 리뷰 감사드립니다!!
단순히 final이 다 해결해주는 것이 아니군요.. 부족한 부분을 찾아주셔서 감사드립니다.
컬렉션의 불변 공부해보겠습니다

2021-12-10 05:48 UTC, bbeomgeun commented on src/main/java/racingcar/model/Cars.java
> +        Optional<Car> winner = carList.stream().max(comparatorByPosition);
아 넵! 테스트 해보겠습니다
null인 경우 get() 호출해보기. 
orElse, orElseThrow 키워드 공부

2021-12-10 06:28 UTC, bbeomgeun commented on src/main/java/racingcar/view/OutputView.java
> +    public void printProgress(Cars carList) {
아, 파라미터로 정해준 타입을 사용하겠다는 의미라고 생각하면 이해가 바로 되네요!!

2021-12-11 04:36 UTC, Be-poz commented on src/main/java/racingcar/model/Car.java
> +        }
1. 넵 필요하면 try catch로 하시면 됩니다. class나 method 옆에 unchecked exception을 모두 표기하기에는 모든 클래스와 모든 메서드에 다 붙이셔야 할 겁니다.. 다 발생하기 때문에요!  

그리고 이후 스프링 같은 것을 사용하게되면 예외를 한 번에 catch해서 처리할 수 있는 방법 또한 있습니다.  

2. 생성자에서 valid조건문을 통과하지 않으면 해당 valid 메서드에서 예외를 터트려주면 될 것 같습니다. 그리고 바깥 controller에서 try catch로 잡으시면 될 것 같네요!

2021-12-11 14:09 UTC, Be-poz commented on src/main/java/racingcar/view/InputView.java
> +    public static String input() {
8번 라인 지우면 좋을 것 같아요~!

2021-12-11 14:09 UTC, Be-poz commented on src/main/java/racingcar/model/Car.java
> +        throw new IllegalArgumentException(NAME_ERROR_MESSAGE);
음 제 말은  
```java
private void validateNameSize(String name) {
         if (name.length() > MAX_NAME_SIZE && name.length() < MIN_NAME_SIZE) {
            throw new IllegalArgumentException(NAME...);
        }
}
```
을 말한거였습니다! 이렇게 한 뒤에  
생성자에서  
```java
Car (String name) {
 validateNameSize(name);
 this.name = name;
}
```
이렇게요! 그리고 현재 바뀐 코드를 보면 true가 아닐 시에 name에 null을 집어넣고 있는데 true가 아니면 exception이 던져지니깐 해당 라인이 의미가 없어질 것 같습니다!  

사실 boolean을 return 할지 아니면 void return으로 두고 내부적으로 exception을 던질지는 취향이긴합니다! 코드에서 보통 많이 보이는 방법이기도 하고 제가 주로 사용하는 방법이어서 의견을 꺼내봤습니다!

2021-12-11 14:09 UTC, Be-poz commented on src/main/java/racingcar/model/Cars.java
> +        return winner.orElseThrow(NoSuchElementException::new).getFinalPosition();
인라인 변수로 표현해도 될 것 같네용

2021-12-11 14:12 UTC, Be-poz commented
이번 미션은 이쯤으로 두고 다음번에 리뷰받은 것 들을 놓치지않고 보완해서 제출하시면 될 것 같습니다. 오리님 수고하셨어요 이만 머지할게요~!  
추가적인 질문은 계속 남겨도 상관없습니다~!

2021-12-11 14:12 UTC, merged

2021-12-11 16:39 UTC, bbeomgeun commented on src/main/java/racingcar/model/Car.java
> +        throw new IllegalArgumentException(NAME_ERROR_MESSAGE);
와, 엄청 획기적이네요! 무조건 boolean 리턴만 생각해서 구조를 좀 어색하게 바꿨는데 아주 맘에 듭니다!!
꿀팁 감사합니다 :)

2021-12-11 16:42 UTC, bbeomgeun commented
파즈님, 리뷰 감사합니다!!
2차 과제에서도 많은 걸 배운 것 같습니다 ㅎㅎ
바쁘신 와중에 시간 내주셔서 정말 감사합니다!!!